#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Display information about subdomains.

domain_information () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  domain_information "$1" "ujolie.tech"
  domain_information "$1" "34.229.92.231"
  domain_information "$1" "54.196.147.72"
  domain_information "$1" "18.213.0.162"
elif [ "$#" == 2 ]
then
  domain_information "$1" "$2"
fi
