#!/bin/bash

# Function to query DNS records for a subdomain
query_dns() {
    local domain=$1
    local subdomain=$2
    
    # Lookup DNS records using dig and awk for parsing
    dig +short $subdomain.$domain | awk -v sub=$subdomain '{print "The subdomain " sub " is a " $1 " record and points to " $NF }'
}

if [ $# -eq 0 ]; then
    echo "Domain and subdomain parameters are required."
    exit 1
fi

domain=$1
subdomain=${2:-www}

case $subdomain in
    www|lb-01|web-01|web-02)
        query_dns $domain $subdomain
        ;;
    *)
        echo "Invalid subdomain."
        exit 1
        ;;
esac
